- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package: 
      name: {{item}}
      state: installed
    loops:
    - mysql
    - nodejs
    - git
