- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: installing packages
    ansible.builtin.package: 
      name: "{{item}}"
      state: installed
    loop:
    - mysql
    - nodejs
    - git
