- name: pass variables
  hosts: web
  vars:
   trainer: Siva
  vars_files:
  - course.yaml
  vars_prompt:
    name: trainer
    prompt: "Enter trainer name:"
  tasks:
  - name: print variables
    # vars: 
    #   trainer: Ashok
    ansible.builtin.debug:
      msg: "Trainer is {{trainer}}"
    
    
