- name: install and start nginx
  host: web
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
       name: nginx
       state: started
    

