- name: configure mysql
  hosts: db
  become : yes
  vars: 
    my_sql_passwd: ExpenseApp@1
  tasks:
  - name: Install Mysql libraries
    ansible.builtin.pip:
      name: {{ item }}
      executable: pip3.9
    loop:
    - cryptography
    - PyMysql
  - name: install mysql 
    ansible.builtin.package:
       name: mysql-server
       state: present
  - name: start mysql
    ansible.builtin.service:
       name : mysqld
       state: started
       enabled: yes
  - name: login check
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{my_sql_passwd}}"
      login_host: mysql.sushu.store
    register: mysql_info
    ignore_errors: true
  - name: set password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{my_sql_passwd}}"
    when: mysql_info.failed is true
